### ISSUE TITLE
build failure: unused result for write()

### ISSUE THREAD

**Issue by eworm-de** [open-iscsi/open-isns#24] opened 2020-01-24 06:41 UTC
As warnings are treated as errors build fails with:

```
pki.c: In function ‘isns_dsa_init_params’:
pki.c:481:2: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
  481 |  write(1, "\n", 1);
      |  ^~~~~~~~~~~~~~~~~
```

**Comment by gonzoleeman** [comment] 2020-01-28 19:46
This is not an issue for me, using gcc-9. It looks like functions must be declared with the attribute warn_unused_result in their include file for gcc to throw this error (as mentioned in the error message you posted). But write() is not declared this way in Tumbleweed.

It would actually make the code kind of ugly to have:

```

(void) printf(...);
(void) close();

```
I used to program that way (before my Linux days), but now it's considered somewhat pedantic.

What distro are you using? Perhaps you need to add -Wno-unused-result?

**Comment by eworm-de** [comment] 2020-01-28 19:52
This is with a recent Arch Linux.
For now I remove -Werror from CFLAGS.

**Comment by gonzoleeman** [comment] 2020-01-29 02:06
I have created a branch to fix just the write() return values. Can you try it out?

github.com/gonzoleeman/open-isns:fix-write-return-value

It just throws "(void)" casts before the write() calls, since we are writing to STDOUT and really don't care about the return value.

**Comment by eworm-de** [comment] 2020-01-29 08:17
No, that does not help:

```
pki.c: In function ‘isns_dsa_init_params’:
pki.c:481:9: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
  481 |  (void) write(1, "\n", 1);
      |         ^~~~~~~~~~~~~~~~~
```

Here is a lengthy discussion about [(void) cast doesn't suppress __attribute__((warn_unused_result))](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425).

**Comment by gonzoleeman** [comment] 2020-01-29 16:23
> On Jan 29, 2020, at 12:17 AM, Christian Hesse <notifications@github.com> wrote:
> 
> No, that does not help:
> 
> pki.c: In function ‘isns_dsa_init_params’:
> pki.c:481:9: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
>   481 |  (void) write(1, "\n", 1);
>       |         ^~~~~~~~~~~~~~~~~
> Here is a lengthy discussion about (void) cast doesn't suppress attribute((warn_unused_result)) <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425>.
> 

Very interesting. I agree with those saying “(void)” cast should fix the problem, but I think in your case the problem is that Arch Linux seems to think it’s just stupid to not check the write() return value, which is just plain wrong. I can see such an attribute for malloc()/remalloc(), but not for write(). Whatever.

Please pull the same branch and try again — I’m checking the return value now. But I really don’t want to have to download Arch Linux to test it myself. :)

— 
Gonzo Lee-Man

**Comment by eworm-de** [comment] 2020-01-29 19:05
> Very interesting. I agree with those saying “(void)” cast should fix the problem,

Me too.

> Please pull the same branch and try again — I’m checking the return value now. But I really don’t want to have to download Arch Linux to test it myself. :) — Gonzo Lee-Man

That builds without warnings. Thanks!

**Comment by gonzoleeman** [comment] 2020-01-29 20:48
Now merged into master, so closing this issue.

**Closed as completed by gonzoleeman** 2020-01-29 20:48 UTC
